### PR TITLE
Remove INSTALL_NAME_DIR from target

### LINKED ISSUE #49: Why is INSTALL_NAME_DIR set on the shp target?
I'm using shapelib on OSX using vcpkg, and it doesn't play very well with everything else which just assumes that installed libraries will be found under `@rpath`--for example:

```
$ otool -L /Users/russellgreene/ars/ext/vcpkg/packages/freetype_arm64-osx-dynamic/lib/libfreetype.6.18.3.dylib
/Users/russellgreene/ars/ext/vcpkg/packages/freetype_arm64-osx-dynamic/lib/libfreetype.6.18.3.dylib:
        @rpath/libfreetype.6.dylib (compatibility version 6.0.0, current version 6.18.3)
        @rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
        @rpath/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.6)
        @rpath/libpng16.16.dylib (compatibility version 16.0.0, current version 16.39.0)
        @rpath/libbrotlidec.1.dylib (compatibility version 1.0.0, current version 1.0.9)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

however, shp looks like

```
$ otool -L /Users/russellgreene/ars/ext/vcpkg/packages/shapelib_arm64-osx-dynamic/debug/lib/libshp.1.dylib
/Users/russellgreene/ars/ext/vcpkg/packages/shapelib_arm64-osx-dynamic/debug/lib/libshp.1.dylib:
        lib/libshp.1.dylib (compatibility version 1.0.0, current version 1.5.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

removing the INSTALL_NAME_DIR directive fixes this and brings it towards "normal" behavior. 

Is there a good reason for this change? If not, would a PR removing it be accepted? Thank you!

### PR DESCRIPTION
**Pull request by thbeu**
Closes #49.

### CODE REVIEW

**Comment by rouault** [comment]
I'm very confused by the MacOSX situation. In the PROJ project, in https://github.com/OSGeo/PROJ/pull/3948, there's a pull request doing the exact reverse thing as your PR...

**Comment by thbeu** [comment]
I am confused as well. I do not set INSTALL_NAME_DIR property in my other project and noticed #49.

**Comment by thbeu** [comment]
@Kitware Do you have any hint for a proper configuartion? Thanks.

**Comment by thbeu** [comment]
@russelltg Can you cross-check if it works on OSX? Thanks.

**Comment by thbeu** [comment]
> I'm very confused by the MacOSX situation. In the PROJ project, in [OSGeo/PROJ#3948](https://github.com/OSGeo/PROJ/pull/3948), there's a pull request doing the exact reverse thing as your PR...

That PROJ PR is now closed w/o merge.

**Comment by thbeu** [comment]
One more try to resolve the confusion; @MaartenBent What is you opinion? Thank you.

**Comment by thbeu** [comment]
I noticed the [1.6.0-0003-relocatable-shared-macos.patch](https://github.com/conan-io/conan-center-index/pull/21894/files#diff-d886cd5612265e3e0712853020ca0928bbd6c9b0a500a7abb962dd6d377133ac) of Conan to exactly fix that issue: https://github.com/conan-io/conan-center-index/pull/21894/files

**Pull request merged**
