### PR TITLE
CI: treat all warnings as errors

### PR DESCRIPTION
**Pull request by thbeu**
See https://github.com/OSGeo/shapelib/pull/82#issuecomment-1903963244

### CODE REVIEW

**Comment by rouault** [comment]
We should definitely *not* put warnings-as-errors in the CMakeLists.txt as default. This is too risky. This should only be set in the CI scripts

**Comment by thbeu** [comment]
> We should definitely _not_ put warnings-as-errors in the CMakeLists.txt as default. This is too risky. This should only be set in the CI scripts

Done. CMake &GreaterEqual; 3.24 is required acording to https://cmake.org/cmake/help/latest/variable/CMAKE_COMPILE_WARNING_AS_ERROR.html#variable:CMAKE_COMPILE_WARNING_AS_ERROR.

**Comment by rouault** [comment]
Do you mind reworking the git history to fold the first 2 commits in a single one? Thanks

**Comment by thbeu** [comment]
> Do you mind reworking the git history to fold the first 2 commits in a single one? Thanks

Check again :-)

**Comment by rouault** [comment]
Excellent. Thanks again for all your work on shapelib

**Comment by thbeu** [comment]
> Excellent. Thanks again for all your work on shapelib

Thanks for the lib after all! I am considerig to work on #16 and #36. Let me know if this is not OK for you.

**Pull request merged**
