### PR TITLE
Ensure consistent definition and declaration of SHPRewindObject

### PR DESCRIPTION
**Pull request by thbeu**
CPL_UNUSED only was used in one place

### CODE REVIEW

**Comment by thbeu** [comment]
Hm. CPL_UNUSED is compiler-specific and I can see compiler-generic implementations for example in 

https://github.com/OSGeo/shapelib/blob/a4b7a3dd0d0d6f34a02fca6e5c6841e9b056e2b4/safileio.c#L33-L36

See https://stackoverflow.com/a/52066370 for other ideas.

**Comment by thbeu** [comment]
That's what I get on MSVC with `/W4 /WX`:

> C:\Users\thbeu\source\repos\shapelib\shpopen.c(2939,54): error C2220: the following warning is treated as an error
C:\Users\thbeu\source\repos\shapelib\shpopen.c(2939,54): warning C4100: 'hSHP': unreferenced formal parameter

**Comment by rouault** [comment]
> That's what I get on MSVC with `/W4 /WX`:

and the (void)foo thing does make it happy ?

ok, trying this proposal in the shapelib copy in GDAL in https://github.com/OSGeo/gdal/pull/9124 to see if other compilers don't warng about the (void)foo pattern

**Comment by rouault** [comment]
ok, GDAL is happy. merging

**Pull request merged**
