### PR TITLE
Disable building GMock and installation of GTest

### PR DESCRIPTION
**Pull request by thbeu**
Neither necessary nor desired.

### CODE REVIEW

**Comment by thbeu** [comment]
@rouault Do you have an idea how to fix the path issue for unit tests (shared objects) on Cygwin? I'd also like to get rid of the install target there. Thx.

**Comment by rouault** [comment]
> Do you have an idea how to fix the path issue for unit tests (shared objects) on Cygwin?

no, sorry

**Comment by thbeu** [comment]
OK.

**Comment by thbeu** [comment]
@rouault Kind reminder for review.

**Pull request merged**
